/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tarcisio' at '9/5/16 10:36 PM' with Gradle 2.13
 *
 * @author tarcisio, @date 9/5/16 10:36 PM
 */
public class Library {
  public static void main(String args[]) {
	  Tela tela = new Tela();
	  tela.run();
  }
}
